### PR TITLE
Fix vega chart data edit, upload, download

### LINKED ISSUE #33: Inline edit of data for charts is buggy
When we currently try to edit the data inline, we are constantly having to click back into the cell.

### LINKED ISSUE #57: Inline edit of data for charts is buggy
When we currently try to edit the data inline, we are constantly having to click back into the cell.

### PR DESCRIPTION
**Pull request by VShian**
fixes #57

### CODE REVIEW

File: src/pages/charts/data_viewer.js [hunk 1]
```diff
@@ -1,101 +1,47 @@
...
-      <Table
-        {...props}
-        className="virtual-table"
+
+      <ReactDataGrid
         columns={mergedColumns}
-        pagination={false}
-        showHeader={true}
-        components={{
-          body: renderVirtualList,
```
Comment (Avinash110) [inline src/pages/charts/data_viewer.js:97]: Does react-data-grid implement virtual scrolling by default ? renderVirtualList does that virtual scrolling part, so why do we need to remove that ?

Comment (VShian) [reply src/pages/charts/data_viewer.js:97]: Yes, react data grid provides virtualized rendering and is efficient for huge datasets.
Refer this https://adazzle.github.io/react-data-grid/docs/implementation-notes

Previous implementation had issues when we want to edit data. It is because it re-renders on every change in input component. Edit is not a functionality provided by previous virtual grid and we have to write our own which is failing due to re-renders. Whereas, react-data-grid has inbuilt edit option which, obviously, will not have such issues since it is inbuilt. It also has lot of other features which could be of a great use for us in future.

Comment (Avinash110) [reply src/pages/charts/data_viewer.js:97]: Oh okay

**Review by Avinash110 — APPROVED** [review]
